language: ruby
sudo: false
rvm:
  - 2.3.1
cache: bundler

services:
  - docker

script:
  - bundle exec rubocop
  - bundle exec rspec --color
  - bundle exec kitchen create -c8
  - bundle exec kitchen converge -c8
  - bundle exec kitchen converge -c8
  - bundle exec kitchen verify
