name 'np-couchpotato'
maintainer 'Nick Pegg'
maintainer_email 'nick@nickpegg.com'
license 'all_rights'
description 'Installs/Configures np-couchpotato'
long_description 'Installs/Configures np-couchpotato'
version '0.1.0'

supports 'debian', '~> 8.0'
supports 'ubuntu', '= 14.04'
