name 'np-couchpotato'
maintainer 'Nick Pegg'
maintainer_email 'nick@nickpegg.com'
license 'all_rights'
description 'Installs/Configures np-couchpotato'
long_description 'Installs/Configures np-couchpotato'
version '0.1.2'

supports 'debian', '~> 8.0'
supports 'ubuntu', '= 14.04'

depends 'application', '~> 5.0'
depends 'apt'
depends 'build-essential'
depends 'poise-service', '~> 1.0'
depends 'python', '~> 1.4.6'
